WITH order_data AS (
  SELECT 
    order_item_id,
    analytic_business_unit,
    analytic_super_category,
    analytic_category,
    analytic_sub_category,
    analytic_vertical,
    brand,
    product_id,
    approved_date_time,
    shipment_type,
    gmv,
    listing_tier,
    order_billing_amount,
    promise_tier,
    new_customer_flag,
    is_alpha_seller,
    marketplace_id,
    shipping_address_pincode_key
  FROM bigfoot_external_neo.cp_bi_prod_sales__forward_unit_history_fact
  WHERE order_date_key >= 20250101
),

toa_fact AS (
  SELECT 
    toa_reference_id,
    sub_entity_reference_id,
    reference_entity_type,
    sub_entity_reference_type,
    toa_type,
    tenant_id,
    promise_date,
    channel,
    created_at,
    external_payment_id,
    updated_at,
    user_login,
    seller_id,
    init_date,
    amount,
    quantity,
    toa_reason,
    customer_request_id,
    merchant_name,
    toa_mode,
    customer_account_id,
    payment_ref_num,
    status,
    entity_version,
    primary_key,
    toa_sub_reason,
    created_day,
    external_reference_id
  FROM bigfoot_external_neo.mp_cs__completed_toa_fact where
  TO_DATE(created_at) >= DATE_SUB(CURRENT_DATE, 31)
),

geo_fact AS (
  SELECT 
    logistics_geo_hive_dim_key,
    city_tier,
    city,
    state
  FROM bigfoot_external_neo.scp_ekl__logistics_geo_hive_dim
),

final_data AS (
  SELECT DISTINCT
    t.external_reference_id,
    CONCAT('OID', o.order_item_id) AS oid,
    t.toa_reference_id,
    t.sub_entity_reference_id,
    t.reference_entity_type,
    t.sub_entity_reference_type,
    o.order_item_id,
    o.analytic_business_unit,
    o.analytic_super_category,
    o.analytic_category,
    o.analytic_sub_category,
    o.analytic_vertical,
    o.brand,
    o.product_id,
    to_date(o.approved_date_time) AS order_approved_date,
    o.shipment_type,
    o.gmv,
    o.listing_tier,
    o.order_billing_amount,
    o.promise_tier,
    o.new_customer_flag,
    o.is_alpha_seller,
    o.marketplace_id,
    t.toa_type,
    t.tenant_id,
    t.promise_date,
    t.channel,
    t.created_at,
    t.external_payment_id,
    t.updated_at,
    t.user_login,
    t.seller_id,
    t.init_date,
    t.amount,
    t.quantity,
    t.toa_reason,
    t.customer_request_id,
    t.merchant_name,
    t.toa_mode,
    t.customer_account_id,
    t.payment_ref_num,
    t.status,
    t.entity_version,
    t.primary_key,
    t.toa_sub_reason,
    t.created_day,
    geo.city_tier,
    geo.city,
    geo.state,
    ROW_NUMBER() OVER (PARTITION BY t.toa_reference_id ORDER BY t.updated_at DESC) AS rnk
  FROM toa_fact t
  LEFT JOIN order_data o ON t.sub_entity_reference_id = o.order_item_id
  LEFT JOIN geo_fact geo ON o.shipping_address_pincode_key = geo.logistics_geo_hive_dim_key
  
)

SELECT DISTINCT
  external_reference_id,
  oid,
  toa_reference_id,
  sub_entity_reference_id,
  reference_entity_type,
  sub_entity_reference_type,
  order_item_id,
  analytic_business_unit,
  analytic_super_category,
  analytic_category,
  analytic_sub_category,
  analytic_vertical,
  brand,
  product_id,
  order_approved_date,
  shipment_type,
  gmv,
  listing_tier,
  order_billing_amount,
  promise_tier,
  new_customer_flag,
  is_alpha_seller,
  marketplace_id,
  toa_type,
  tenant_id,
  promise_date,
  channel,
  date(created_at) as created_at,
  external_payment_id,
  Date(updated_at) as updated_at,
  user_login,
  seller_id,
  init_date,
  amount,
  quantity,
  toa_reason,
  customer_request_id,
  merchant_name,
  toa_mode,
  customer_account_id,
  payment_ref_num,
  status,
  entity_version,
  primary_key,
  toa_sub_reason,
  created_day,
  city_tier,
  city,
  state,
  rnk
FROM final_data
WHERE rnk = 1